version: '2.3'
services:
  nginx-phpfpm:
    build: ./nginx-php-fpm
    container_name: lemp-nginx-phpfpm
    environment: 
      - ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=remote_host=192.168.3.18
      - PHP_IDE_CONFIG=serverName=docker
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html
    networks:
      - lemp-network

  mysql:
    image: mysql:5.7
    container_name: lemp-mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: asdf
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge
