version: '2.3'
services:
  apache-phpfpm:
    image: webdevops/php-apache-dev:centos-7-php56
    container_name: apache-phpfpm
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_DATE_TIMEZONE="Asia/Tokyo"
      - PHP_DEBUGGER=xdebug
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html
      - ./php-conf/php.ini:/opt/docker/etc/php/php.ini
    networks:
      - lemp-network

  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: school_dev
      MYSQL_PASSWORD: school_dev
      MYSQL_DATABASE: school_dev
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge
