version: '2.3'
services:
  apache:
    image: webdevops/php-apache-dev:centos-7-php56
    container_name: apache-php
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_DATE_TIMEZONE="Asia/Tokyo"
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_AUTOSSTART=On
      - XDEBUG_REMOTE_CONNECT_BACK=Off
      - XDEBUG_REMOTE_ENABLE=On
      - XDEBUG_REMOTE_HOST=docker.for.mac.localhost
      - XDEBUG_REMOTE_PORT=9001
      - XDEBUG_PROFILER_ENABLE=On
      - XDEBUG_REMOTE_LOG="/var/www/html/application/logs/xdebug.log"
    depends_on:
      - mysql
      - mailhog
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html
      - ./php-conf/20-php-custom.sh:/opt/docker/provision/entrypoint.d/10-php-custom.sh
      - ./php-conf/php.ini:/opt/docker/etc/php/php.ini
      - ./httpd:/opt/docker/etc/httpd/vhost.common.d
    networks:
      - lemp-network

  mysql:
    image: mysql:5.6
    # command: --character-set-server=utf8mb4 --default-character-set=utf8mb4
    container_name: mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: school_dev
      MYSQL_PASSWORD: school_dev
      MYSQL_DATABASE: school_dev
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
      # - ./mysql/var:/var/lib/mysql
    restart: always
    networks:
      - lemp-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
     - "1025:1025"
     - "8025:8025"
    restart: always
    networks:
     - lemp-network

networks:
  lemp-network:
    driver: bridge
