version: '2.3'
services:
  nginx-phpfpm:
    image: richarvey/nginx-php-fpm:latest
    container_name: lemp-nginx-phpfpm
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html
    networks:
      - lemp-network

  mysql:
    image: mysql:5.7
    container_name: lemp-mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: asdf
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge
