version: '2.3'
services:
  nginx-phpfpm:
    image: richarvey/nginx-php-fpm:latest
    container_name: lemp-nginx-phpfpm
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html
    networks:
      - lemp-network

  mysql-data:
    image: busybox
    container_name: lemp-mysql-data
    volumes:
      - ./mysql/storage:/var/lib/mysql

  mysql:
    image: mysql:latest
    container_name: lemp-mysql
    ports:
      - "3306:3306"
    volumes_from:
      - mysql-data
    volumes: 
      - ./mysql/conf/:/etc/mysql/conf.d
      - ./mysql/log/:/var/log/mysql
      - ./mysql/storage:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: asdf
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge
