version: '2.3'
services:
  nginx:
    image: nginx:1.13.7
    container_name: lemp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/:/etc/nginx/:ro
      - ./nginx/site/:/usr/share/nginx/html/
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - phpfpm
    networks:
      lemp-network:
        ipv4_address: ${LEMP_NGINX}

  phpfpm:
    image: blacksource/php7-fpm
    container_name: lemp-phpfpm
    expose: 
      - "9000"
    volumes:
      - ./phpfpm/conf/fpm/php.ini:/etc/php/7.0/fpm/php.ini
      - ./phpfpm/conf/fpm/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      - ./phpfpm/conf/cli/php.ini:/etc/php/7.0/cli/php.ini
      - ./nginx/site/:/usr/share/nginx/html
    networks:
      lemp-network:
        ipv4_address: ${LEMP_PHPFPM}

  mysql-data:
    image: busybox
    container_name: lemp-mysql-data
    volumes:
      - ./mysql/storage:/var/lib/mysql

  mysql:
    image: mysql:5.7.20
    container_name: lemp-mysql
    ports:
      - "3306:3306"
    volumes_from:
      - mysql-data
    volumes: 
      - ./mysql/conf/:/etc/mysql/conf.d
      - ./mysql/log/:/var/log/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: asdf 
    networks:
      lemp-network:
        ipv4_address: ${LEMP_MYSQL}

networks:
  lemp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LEMP_SUBNET}
          gateway: ${LEMP_GATEWAY}